steps:
# Pull the existing image
 - name: 'gcr.io/cloud-builders/docker'
   id: Pull image
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/tomcat:latest || exit 0
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   id: Build image
   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tomcat', '--cache-from', 'gcr.io/$PROJECT_ID/tomcat', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   id: push image to container registry
   args: ["push", "gcr.io/$PROJECT_ID/tomcat"]


